name: Build and deploy Node.js app to Azure Web App - linky

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Adjust if necessary

      - name: npm install, build, and test
        run: |
          cd backend  # Ensure we're in the backend folder
          npm install
          npm run build --if-present
          

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend  # Specify the backend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03CD81C67A6043508D200F8210570063 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E4C52D511C246B183D2C1F422C9D7F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EE5899D9732842E2AC03DDBFF309D4F3 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'linky'  # Your Azure App Service name
          slot-name: 'Production'
          package: ./backend  # Ensure we're deploying only the backend folder
